[package]
name = "jigamstick"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = "4.5.48"
csv = "1.3.1"
getset = "0.1.6"
hidapi = "2.6.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
statrs = "0.18.0"
